Parse Audio
zacrash/Genie pull request #1
Opened 2017-11-14 05:02 UTC by shanntom

speech recognition parsing

2017-11-14 21:51 UTC, zacrash requested changes
Can you add node-modules to the .gitignore?

2017-11-15 01:25 UTC, shanntom commented
done!

2017-11-16 22:53 UTC, zachrash commented
Can you add the json authentication to an api/private folder (specified in .gitignore)

2017-11-16 23:13 UTC, zacrash approved these changes

2017-11-16 23:14 UTC, merged